site_name: ReJSON - a JSON data type for Redis
site_url: http://rejson.io
repo_url: https://github.com/RedisLabsModules/ReJSON
repo_name: RedisLabsModules/ReJSON

google_analytics:
    - 'UA-92003007-8'
    - 'auto'

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

pages:
    - 'Quickstart': 'index.md'
    - 'Commands': 'commands.md'
    - 'Path syntax': 'path.md'
    - 'Performance': 'performance.md'
    - 'RAM usage': 'ram.md'
    - 'Developer notes': 'developer.md'
    - 'Contributor agreement': 'contrib.md'

   
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
