name: Coverage analysis

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # fetch all history for accurate results
    - name: Setup specific
      working-directory: .install
      run: |
        ./install_script.sh sudo
    - name: Setup common
      run: |
        ./.install/common_installations.sh sudo
    - name: Install clang 18
      working-directory: .install
      run: |
        ./install_clang.sh sudo
    - name: Get Redis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./deps/readies/bin/getredis --with-github-token
    - name: Build and test
      run: make coverage QUICK=1 SHOW=1 LOG=1
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: bin/linux-x64-debug-cov/cov.info
        fail_ci_if_error: true # Fail on upload errors
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Coverage logs
        path: tests/**/logs/*.log*
        if-no-files-found: ignore