name: build for mariner2

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -o pipefail {0}
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - run: |
          tdnf install --noplugins --skipsignature -y ca-certificates git
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: install dependencies
        run: |
          bash .install/mariner2.sh
      - name: get redis latest
        run: |
          bash .install/get_redis.sh
      - name: build and test
        run: |
          make test
      - name: pack module
        run: |
          make pack

# todo: upload artifacts to S3
